export const DEFAULT_SHEET_DATA = [
  {
    name: 'Sheet1',
    celldata: [],
    config: {},
    order: 0,
    row: 500,
    column: 36,
  },
];

export const TOOL_BAR_ITEMS = [
  'undo',
  'redo',
  '|',
  'font',
  '|',
  'font-size',
  '|',
  'bold',
  'italic',
  'strike-through',
  '|',
  'font-color',
  'background',
  '|',
  'border',
  'merge-cell',
  '|',
  'horizontal-align',
  'text-wrap',
  'vertical-align',
  '|',
  'currency-format',
  'percentage-format',
  'number-decrease',
  'number-increase',
  'format',
  '|',
  'conditionFormat',
  'filter',
  '|',
  'link',
  'comment',
  'image',
  'quick-formula',
  'dataVerification',
  'search',
];

export const CELL_CONTEXT_MENU_ITEMS = [
  'cut',
  'copy',
  'paste',
  'clear',
  '|',
  'insert-row',
  'insert-column',
  'cell-delete-row',
  'cell-delete-column',
  // "delete-cell",
  // "hide-row",
  // "hide-column",
  // "set-row-height",
  // "set-column-width",
  '|',
  'conditionFormat',
  'filter',
  'searchReplace',
  'dataVerification',
  'ascSort',
  'desSort',
  '|',
  'chart',
  // 'image',
  'link',
  'data',
  'cell-format',
  'comment',
  'freeze-row',
];

export const HEADER_CONTEXT_MENU_ITEMS = [
  'cut',
  'copy',
  'paste',
  'clear',
  '|',
  'insert-row',
  'insert-column',
  'delete-row',
  'delete-column',
  // "delete-cell",
  'hide-row',
  'hide-column',
  'set-row-height',
  'set-column-width',
  '|',
  'conditionFormat',
  'filter',
  // 'searchReplace',
  'dataVerification',
  'ascSort',
  'desSort',
  '|',
  // 'chart',
  // 'image',
  // 'link',
  'data',
  'cell-format',
  // 'comment',
  'split-text',
  'freeze-row',
  'freeze-column',
];

export const CELL_COMMENT_DEFAULT_VALUE = {
  height: null,
  isShow: false,
  left: null,
  top: null,
  value: '',
  width: null,
};
